image: python:3.6


stages:
  - test


unittest:
  stage: test
  services:
  - name: singularities/datastore-emulator
    entrypoint: ["./start-datastore", "--consistency=1.0"]
  variables:
    DATASTORE_LISTEN_ADDRESS: '0.0.0.0:8081'
    DATASTORE_PROJECT_ID: 'ml2grow-intern'
    DATASTORE_EMULATOR_HOST: '127.0.0.1:8081'
  before_script:
    - pip install nox
  script:
    - nox -s unit


lint:
  stage: test
  before_script:
    - pip install nox
  script:
    - nox -s lint
